FROM alpine:3.16

WORKDIR /root/producer

RUN apk add --update --no-cache python3 py3-pip

COPY requirements.txt .
COPY producer.py .
COPY coords.csv .

RUN pip3 install -r requirements.txt

CMD [ "python3", "producer.py" ]
